CALL \UK-ICS\DRIVER\LL-CASES-LAWREPORT-to-LA-CASES-LAWREPORT_XSPEC.bat
CALL \UK-ICS\DRIVER\LL-DICTIONARYDOC-to-LA-DICTIONARYDOC_XSPEC.bat
CALL \UK-ICS\DRIVER\LL-Index-to-LA-Index_XSPEC.bat
CALL \UK-ICS\DRIVER\LL-Journal-to-LA-Journal_XSPEC.bat